### ISSUE TITLE
Provide a pool of build machines with both VS and LCOW enabled

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/arcade#10766]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As part of the dotnet/runtime official build, we have a few cases where we need to have a job that waits on jobs from multiple different platforms to assemble artifacts and run some additional logic.

Azure DevOps now has a concept of [step targets](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/target?view=azure-pipelines) that allows a job to run different steps inside of different containers. This feature would allow us to save on some of these jobs by combining them into a single job. However, the use case that would most positively affect the dotnet/runtime repo would be a combination of Windows and Linux jobs, which today is unsupported.

If we could have an image option for the Windows build pools that has both VS and LCOW (Linux containers on Windows), we could build both the Windows and Linux components of the artifact in the same job and reduce our official build times by reducing queue times and join jobs.

**Comment by MattGal** [comment]
@jkoritzinsky it looks like we'd need to change the version of docker we put on the compatible build agents (likely Build.Server.Amd64.VS2019 / Build.Server.Amd64.VS2019.Open) to be _able_ to do this.

After doing that, one should be able to switch container modes in yaml between steps like so.  Would this be an acceptable compromise?  If so I can probably get the Build.Server.Amd64.VS2019 image updated for next week with the preview Docker engine that supports this. 

```
    - task: PowerShell@2
      name: useLinuxContainers
      displayName: Switch Docker to Linux container mode
      inputs:
        targetType: inline
        script:
          [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
          Restart-Service docker
```
