### ISSUE TITLE
How to override a task "continueOnError" to have a condition with variables?

### ISSUE THREAD

**Issue by psfinaki** [dotnet/arcade#13239]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description

Hey, this is actually just a question. We have a [pipeline](https://github.com/dotnet/fsharp/blob/main/azure-pipelines.yml), here's a simplified part of it. What I am trying to do is to have `continueOnError` true in case of integration tests.

```yaml
- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    ...
    jobs:
    - job: JOB
      ...
      strategy:
        maxParallel: 3
        matrix:
          desktop_release:
            _configuration: Release
            _testKind: testDesktop
          vs_release:
            _configuration: Release
            _testKind: testVs
          inttests_release:
            _configuration: Release
            _testKind: testIntegration

      steps:
      - checkout: self
        clean: true

      - script: eng\CIBuild.cmd -configuration $(_configuration) -$(_testKind)
        displayName: Build / Test
        continueOnError: eq(variables['_testKind'], 'testIntegration')
```

And so this doesn't work:
![image](https://user-images.githubusercontent.com/5451366/233492299-c08e6379-ff95-4965-9e33-4c7123018e54.png)

Looks like the way templates work, it's just not possible to set such an expression there. Only `true` or `false`. 
But this works for conditions! Hence the best workaround I have found is this - very lame:

```yaml
- script: eng\CIBuild.cmd -configuration $(_configuration) -$(_testKind)
  displayName: Build / Test
  condition: ne(variables['_testKind'], 'testIntegration')

- script: eng\CIBuild.cmd -configuration $(_configuration) -$(_testKind)
  displayName: Build / Integration Test
  continueOnError: true
  condition: eq(variables['_testKind'], 'testIntegration'
```

How to do this properly? I am sure there should be a better way but I am pulling my hair for two hours already with this.
