### ISSUE TITLE
Document allowed values for BAR subscriptions

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1524]
I was following https://github.com/dotnet/arcade/blob/master/Documentation/DependencyFlowOnboarding.md, which provides some sample values for configuring BAR subscriptions. Where can I find more details on allowable settings?

For instance, the docs show this: 
```yml
Channel: .NET Tools - Latest
# ...
Merge Policies:
- Name: AllChecksSuccessful
  Properties:
    ignoreChecks:
    - WIP
    - license/cla
```
Questions:

* The interactive prompt shows two suggested channels. Where can I see a list of all available channels?
* What other merge policies are available?
* What other properties are allowed `AllChecksSuccessful` merge policy?
* How do the merge policies apply to PRs made in Azure Repos?

FWIW - I see some of this is documented in code (https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/AddSubscriptionPopUp.cs), but it only appears if you run `add-subscription` in interactive mode. Would be nice to make this content available in documentation without having to execute a command which modifies subscription state.
