### ISSUE TITLE
Enable incremental binary analysis

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#15527]
Enable incremental binary SDL analysis in pipelines and the staging pipeline for caching performance gains:

```
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    featureFlags:
      incrementalSDLBinaryAnalysis: true
```
