### ISSUE TITLE
Support passing additional properties to the vsmanproj 

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#1681]
As discussed with @tmat - we'd like to be able to produce *finalized* vsman files from our build. We can do this today with gross workarounds, but would like this to become a documented/supported technique.

We need to inject additional MSBuild properties here: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.InsertionManifests.targets#L26
Example (HACKED) usage: https://github.com/aspnet/AspNetCore-Tooling/blob/master/eng/AfterSigning.targets#L3

**Comment by tmat** [comment]
I’m currently leaning towards the following design:

The repo will declare variable in YAML like so:

```yml
VisualStudioDropName: Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)
```

and then pass it to the build script:

```yml
- script: eng\common\CIBuild.cmd 
            ...
            /p:OfficialBuildId=$(Build.BuildNumber)
            /p:VisualStudioDropName=$(VisualStudioDropName)
            ...
```

This will then flow to the vsmanproj where we will set `ManifestPublishUrl` based on `VisualStudioDropName`.

The value is also needed in `MicroBuildUploadVstsDropFolder` pipeline task that uploads the VSIXes to VSTS drops:

```yml
- task: ms-vseng.MicroBuildTasks.4305a8de-ba66-4d8b-b2d1-0dc4ecbbf5e8.MicroBuildUploadVstsDropFolder@1
  displayName: Upload VSTS Drop
  inputs:
    DropName: $(VisualStudioDropName)
    DropFolder: 'artifacts\VSSetup\$(BuildConfiguration)\Insertion'
    condition: succeeded()
```
