### ISSUE TITLE
Telemetry onboarding documentation is out of date

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#2100]
https://github.com/dotnet/arcade/blob/78ccbeb1c8de779a6650257b408f5b3b4de16a0f/Documentation/CorePackages/Telemetry.md

```yml
- phase: Build
  steps:
  - template: eng/common/templates/steps/telemetry.yml
    parameters:
      helixType: build/product/
      helixSource: official/helix/$(Build.SourceBranch)/
      buildConfig: $(BuildConfiguration)
      steps:
      - template: /eng/configure.yaml
      - template: /eng/restore.yaml
      - template: /eng/build.yaml
```

`eng/common/templates/steps/telemetry.yml` doesn't exist, and `phase` is the old schema.

The earlier parts might be out of date, too, but I'm not familiar with the Arcade templates yet. (I was looking at this because I was asked why core-setup isn't using Arcade telemetry.)

/cc @chcosta @MattGal @robertborr
