### ISSUE TITLE
_DotNetValidationArtifactsCategory misspelled as _DotNetValidationArtifactCategory in YamlStagesPublishing.md

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/arcade#3590]
https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/YamlStagesPublishing.md misspells `_DotNetValidationArtifactsCategory `as `_DotNetValidationArtifactCategory` (missing `s`) in a couple of places. 

Setting it like this as shown in the documentation results in failed builds: 

```yml
variables:
...
  - name: _DotNetValidationArtifactCategory
    value: MyNewCategory
```

It should instead be set like this: 
```yml
variables:
...
  - name: _DotNetValidationArtifactsCategory
    value: MyNewCategory
```
