### ISSUE TITLE
Check correct usage of variable declaration/reference after variable template files

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3874]
Check that we can do the below in AzDO YAML and fix the usage here and here.

```
stages:
- stage:
  variables:
    - template: ../common-variables.yml
    - name: var
      value: 'value'
  steps:
    ...
    # should we use $(var) or ${{ var }}
    # do any of these work?
```

/cc @mmitche @chcosta
