### ISSUE TITLE
CI builds should publish binary logs

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#403]
The logs are currently not available for CI builds.

Something like should do:

```
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: logs'
  inputs:
    PathtoPublish: 'artifacts\$(BuildConfiguration)\log'
    ArtifactName: logs
  condition: succeededOrFailed()
```
