### ISSUE TITLE
BAR publish stages are causing Azure DevOps to overflow, preventing seeing status of builds

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#5735]
- [X] This issue is blocking 
- [X] This issue is causing unreasonable pain

BAR injecting a stage for every channel that exists in the world is unsustainable. It's gotten so bad that I can't tell if my builds are passing or failing any more:
![image](https://user-images.githubusercontent.com/11790765/86303977-53129e00-bbc2-11ea-9afa-d78385082f5a.png)

Important stages are being pushed off the UI on the right because of all the BAR stages.

If you look at what all those weird little check boxes are, they are a bunch of publishing stages:
![image](https://user-images.githubusercontent.com/11790765/86304063-8a814a80-bbc2-11ea-88ea-8d7c231b8e15.png)

**Comment by ChadNedzlek** [comment]
Why do they have to be their own stages and not multiple jobs in the same stage? Or even just steps in a single job.  Having them be so top level is making it hard to make sense of my builds.

**Comment by ChadNedzlek** [comment]
Actually, I'm upgrading this to blocking. Being able to tell if a builds are passed or failed is critical information.  Without having to open ever single build.

**Comment by riarenas** [comment]
The good news is that there's work currently underway to make this a single stage with multiple jobs (along with other improvements such as using way less YAML).

@epananth Could you please close this as a dupe against the publishing issues you're working on?

**Comment by dagood** [comment]
I have this Stylus rule in place to work around this:

```css
/*
Shrink the status label bubbles and especially the '-' lines, so all are
visible on build browser (helps when there are many).
*/

span.flex-row.flex-center > span.flex-row.flex-center + .bolt-status {
    display: none;
}

a > .bolt-status.flex-noshrink {
    width: 10px;
}
```

> ![image](https://user-images.githubusercontent.com/12819531/86795574-5202c600-c033-11ea-83ef-97810d61acef.png)
>
> ![image](https://user-images.githubusercontent.com/12819531/86795656-68108680-c033-11ea-8fd0-eef75ee63fa0.png)


This has been an issue for a long time in core-setup/runtime. Glad to see the arcade side is going to be worked on. 😄
