### ISSUE TITLE
[Signing] Add task to call signproxy sdk task in sign-prep.yaml for dotnet-release

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5915]
Blocked on this until a version of Arcade that contains this commit is promoted: https://github.com/dotnet/arcade/commit/0cae6578b2aa43b94dcfa1d68db30606adc043db

After this is available, we can add task to sign-prop.yaml in dotnet-release: 

```
            - task: PowerShell@2
              displayName: Sign Proxy
              inputs:
                filePath: eng\common\sdk-task.ps1
                arguments: -task SignProxy -restore -msbuildEngine vs
                  /p:OfficialBuild=true

            - task: CopyFiles@2
              displayName: Copy Files to $(Build.StagingDirectory)\BuildLogs
              inputs:
                SourceFolder: '$(Build.SourcesDirectory)'
                Contents: |
                  **/*.log
                  **/*.binlog
                TargetFolder: '$(Build.StagingDirectory)\BuildLogs'
              continueOnError: true
              condition: succeededOrFailed()

            - task: PublishPipelineArtifact@1
              displayName: Publish BuildLogs
              inputs:
                targetPath: '$(Build.StagingDirectory)\BuildLogs'
                artifactName: ${{ parameters.logArtifactName }}
              condition: succeededOrFailed()
```
