### ISSUE TITLE
Release repository tests need to fail PR builds if they fail

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#6306]
There are test failures in master, and PR's don't validate that new failures aren't being introduced.

**Comment by ChadNedzlek** [comment]
I tried to take a stab at this, but the tests are run in some crazy powershell file that does all sorts of weird things... it's not just a simple call to "dotnet test dotnet-release.sln" with arguments, so I have no idea how to make it work.

**Comment by adiaaida** [comment]
I did not know this was a thing... example?

**Comment by missymessa** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=840109&view=ms.vss-test-web.build-test-results-tab&runId=26750402&resultId=100017&paneView=debug

Here's one of the builds from Chad's PRs. Looking at the test tab, there are failing tests, but the build is green when it really should've failed.

**Comment by ChadNedzlek** [comment]
EVERY PR is failing, because there are 4 failing tests in main. :-) (Which also isn't red)

**Comment by adiaaida** [comment]
OMG.

**Comment by adiaaida** [comment]
This.... has been changed recently? We used to do:

```
- task: DotNetCoreCLI@2
        displayName: Test C# (dotnet test)
        inputs:
          command: 'custom'
          projects: |
            **/*.Tests.csproj
            **/*[Tt]ests/*.csproj
          custom: 'test'
          arguments: > 
            --configuration $(BuildConfiguration)
            --collect:"Code Coverage"
            --settings:CodeCoverage.runsettings
            --filter "TestCategory!=PostDeployment&TestCategory!=Nightly&TestCategory!=PreDeployment"
            --no-build
            --no-restore
            --logger trx
```

and now we do 

```
- task: Powershell@2
        inputs: 
          targetType: 'filePath'
          filePath: eng\runtests.ps1
          arguments: -ci -configuration Release -codeCoverageResultsDirectory $(Build.SourcesDirectory)\artifacts\coverage\results\
        displayName: Test
        env:
          maestro-scenario-test-github-token: $(maestro-scenario-test-github-token)
          maestro-scenario-test-azdo-token: $(dn-bot-dnceng-build-rw-code-rw-release-rw)
          dotnetcli-connection-string: $(dotnetcli-connection-string)
```

which is a thing @chcosta changed. Chris, do you know why tests that are failing are being marked as passed with runtests.ps1? I have definitely seen testing fail before this change. For example: https://dnceng.visualstudio.com/internal/_build/results?buildId=821694&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=4cf9c106-f8f4-5b50-808b-a1dd5e6dbc8a
